name: Day 1 - First Pipeline

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: |
          pwd
          ls -la
      - name: Validate index.html exists
        run: |
              test -f index123.html
              echo "✅ index.html file exists"
