name: Day 3 - Build and Test Pipeline
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build step (dummy build)
        run: |
          echo "🔨 Build started"
          ls -la
          echo "✅ Build completed"
          

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test index.html exists
        run: |
          test -f index.html
          echo "✅ Test passed: index.html exists"
          
      - name: Print normal variable
        run: echo "Normal var = $MY_VAR"
        env:
          MY_VAR: "I am normal text"

      - name: Use secret (will be masked)
        run: echo "Secret value = $DEMO_SECRET"
        env:
         DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
  docker:
      needs: test
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t my-nginx-demo .

      - name: Run Docker container
        run: docker run -d -p 8080:80 --name web my-nginx-demo


      
      - name: Test container with curl (wait for nginx)
        run: |
         echo "Waiting for container to be ready..."
         for i in {1..5}; do
         if curl -s http://localhost:8080; then
         echo "✅ Container is up"
         exit 0
         fi
         sleep 2
         done
         echo "❌ Container not reachable"
         exit 1



